### ISSUE TITLE
gitchart at PyPI

### ISSUE THREAD

**Issue by slavkoja** [flashcode/gitchart#5]
The gitchart is installable via pip, but it provides the 0.0.1 version, see (python 3.5):
```
pip search gitchart
gitchart (0.0.1)  - Build SVG charts from a git repository
```
After i better look into it, it points to fork at https://github.com/graingert/gitchart, see more here https://pypi.python.org/pypi/gitchart. I don't know what to do with this, but it is a confusing situation.

**Comment by flashcode** [comment]
Hi,

Oh I just discovered this package on Pypi.

This is related to PR #4. I'm about to push changes (including a setup.py) and upload the package on Pypi myself, so @graingert could you please remove your package on Pypi, so that I can manage it myself?

Thanks.

**Comment by graingert** [comment]
@slavkoja 0.0.2 is the latest version including all the changes up to #5959301

**Comment by flashcode** [comment]
Hi @graingert,

As the main developer, I would like to manage myself gitchart on Pypi.
So could you please remove your Pypi package called "gitchart"?
Or feel free to change its name.

I'll then push my changes and upload on Pypi, with the appropriate "official" version (1.4-dev), built from this repository.

Thanks.

**Comment by graingert** [comment]
@flashcode I'll add you as maintainer to https://github.com/gitchart/gitchart/ and PyPI https://pypi.python.org/pypi/gitchart but please do not delete the old versions (0.0.1 and 0.0.2) as that will break the existing users.

**Comment by flashcode** [comment]
@graingert: Versions 0.0.1 and 0.0.2 are not something official, I never released such versions.
So this is confusing for users, and it does not make sense for me to keep such "forked" versions, wich a different number.

And please don't set me as a maintainer of your forked package, I want to be the owner of gitchart on Pypi, which makes sense to me since I'm the developer.

Thanks.

**Comment by graingert** [comment]
I see you have no interest in keeping versions 0.0.1 and 0.0.2 to avoid breaking existing users, so I am unable to add you as a maintainer to gitchart on PyPI.

**Comment by flashcode** [comment]
OK, then please just remove your "gitchart" package from Pypi, I'll upload mine, which is the official one.

And I see you created an organization on github as well.

If you want to have total control on gitchat, please fork the project under another name (which is the good way to do with free software), make your changes or whatever you want (respecting the GPLv3 license) and please do not use the name "gitchart" anywhere.

Thanks.

**Comment by flashcode** [comment]
@graingert: So I'll sum up the situation.

You did that:

* Creation of a pull request on Feb 1st, with many changes. I don't agree on some of thems, and I explained that in my answer on Feb 19th.
* Upload of a "gitchart" package on Pypi, without asking me, with a wrong version number and a different content than the original/official one (I mean this repository).
* Creation of a GitHub organization called "gitchart", containing the fork of my project, without asking me.

I consider that the Pypi package "gitchart" and GitHub organization with the same name were created to fool the users.
They think they'll install the gitchart package built from my repository, but that's not the case.

So I can not guarantee at all what is included in your Pypi package, and then can not give any guarantee to people installing that.

Yesterday I added a setup.py script in gitchart, so I'm now ready to upload the gitchart package on Pypi.

Therefore, @graingert I kindly ask you to:

1. Remove the Pypi package called "gitchart", so that I can upload there the official one. If you want really to distribute gitchart on Pypi, please choose another name. You never asked me the authorization to publish this package with the same name, and I never gave such authorization to you or someone else.

2. Remove the GitHub organization as well, which is for me just a way to fool users even more (they could think the repository in this organization is the official one). If you want to manage this project in an organization, please fork my project under another name (respecting the GPLv3 license) and create an organization with this name.

If you refuse to do these changes, I'll have to:

1. Contact Pypi admin to force the removal of your fake and untrusted package called "gitchart".

2. Contact GitHub to force the removal of the "gitchart" organization.

3. Add a warning in gitchart README with your name, saying that you stole the name on Pypi, and then I recommend to the users to **NEVER** install your fake and untrusted package, since I have no guarantee about what you are putting inside now and in the future.

I hope I'll not have to do that, and I hope you'll understand that what you did is an error. You can quickly undo that and this would be nice from you.

Thanks.

**Comment by graingert** [comment]
Hey there, 

I'm not going to delete the package from PyPI: I don't want to break existing users of the package and I don't want someone to sneak in and register gitchart that's not you while it's gone. 

I didn't create the github organisation to fool people, I created it so I could hand over ownership of my code under a sensible name: I've already invited you to the github gitchart organisation.

I'm also totally happy to add you to the gitchart PyPI project as long as you don't delete the existing versions. 

I kept the versions low: 0.0.1, 0.0.2 so that I don't collide with versions that are added in the future.

**Comment by flashcode** [comment]
@graingert: OK, I'm sad to see you didn't understand it's an error to use the same name to fool the people with different contents.

The "existing users" as you called them are already fooled by your packages, they **DIDN'T** download the official "gitchart", but a fake copy that you made, using the same name.
**I strongly disagree with that.**

So I'm going to add a warning in the README, saying that you usurped the project name to provide a modified version on Pypi without authorization. And I'll recommend users to **NOT** install your untrusted package.
People will then be informed that you have bad practices and that you refuse to change anything.

@slavkoja: I'm sorry but as you can read @graingert wants to keep its fake/untrusted package on Pypi. So I'll contact Pypi admins to force removal of this package. In the meanwhile, I recommend to **NOT** use the "gitchart" package on Pypi, since I can not guarantee its content.

**Comment by graingert** [comment]
Remember I'm totally happy to add you to the project on PyPI, and the github organisation. Just don't break anyone's builds.

For example, instead of deleting my versions, you could hide them.

**Comment by flashcode** [comment]
I don't want to be a member of anything for my own project and depend on you.
I created the project and am the only maintainer, OK?
If someone asks me to be the maintainer of the package on Pypi or anywhere else, this can be discussed. But asking is the first mandatory step.

So anything you create with the name "gitchart" and a different content is made to mislead the users, and as I said, **I strongly disagree with this practice**.

I'm now adding your name as usurper in the README, to warn people about your practices.
I'm sorry for doing that, but you are forcing me to do it. Misleading the users is just unacceptable for me.

Now I'm closing this issue, I wasted enough time with that.

Regards,
Sébastien.

**Comment by slavkoja** [comment]
IMO, it was not to be closed, to users can find this discussion, until it will be resolved and pypi will have correct version.

IMO, the @graingert package violates the GPL and you (as author) can ask both, the pypi and github, to remove their packages, because they are simple fake, because original is not abandoned and under active development.

**Comment by flashcode** [comment]
@slavkoja: you're right, I'll keep this issue open until I manage to force the removal of untrusted package.

**Comment by flashcode** [comment]
Hooray! The transfer of the PyPI package is done, and I pushed the latest version 1.5.
So I can finally close this issue.
